### ISSUE TITLE
Cannot load PRX

### ISSUE THREAD

**Issue by ItsJokerZz** [DeathRGH/libframe4-cs#1]
```markdown
System.Exception
  HResult=0x80131500
  Message=libframe4 status 0xF0000003 CMD_DATA_NULL
  Source=project
  StackTrace:
   at libframe4.FRAME4.CheckStatus() in C:\Users\Dakota\Desktop\project\Resources\libframe4\FRAME4.cs:line 351
   at libframe4.FRAME4.LoadPRX(String procName, String prxPath) in C:\Users\Dakota\Desktop\project\Resources\libframe4\FRAME4.Proc.cs:line 920
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at project.app.button1_Click(Object sender, EventArgs e) in C:\Users\Dakota\Desktop\project\app.cs:line 233
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at project.Program.Main() in C:\Users\Dakota\Desktop\project\Program.cs:line 19

**Comment by ItsJokerZz** [comment]
ive tried both of the following, as i was unsure of the usage.
```cs
api.LoadPRX("eboot.bin", Path.Combine(Path.Combine(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location), "payloads"), "project.sprx"));

api.LoadPRX("eboot.bin", "/data/project.sprx"));
